apiVersion: v1
kind: Service
metadata:
  name: flaskdemo1
spec:
  selector:
    app: flaskdemo1
  type: LoadBalancer
  ports:
    - name: docker-port
      protocol: TCP
      port: 5000
      targetPort: 5000
