---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dentari
  labels:
    app: dentari
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    # cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
    - secretName: dentari-edentlab-hu-tls
      hosts:
        - dentari.edentlab.hu
  rules:
    - host: dentari.edentlab.hu
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: dentari
                port:
                  number: 8501
