---
apiVersion: v1
kind: Service
metadata:
  name: dentari
  labels:
    app: dentari
  annotations:
    metallb.universe.tf/loadBalancerIPs: "192.168.0.106"
spec:
  selector:
    app: dentari
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 8501
      targetPort: 8501
  loadBalancerIP: 192.168.0.106
