apiVersion: v1
kind: List
items:
  - apiVersion: networking.k8s.io/v1
    kind: Ingress
    metadata:
      name: dev-dentari
      namespace: dev-dentari
      labels:
        app: dev-dentari
      annotations:
        kubernetes.io/ingress.class: traefik
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
    spec:
      tls:
        - secretName: dev-dentari-tls
          hosts:
            - dev-dentari.edentlab.hu
      rules:
        - host: dev-dentari.edentlab.hu
          http:
            paths:
              - path: /
                pathType: Prefix
                backend:
                  service:
                    name: dev-frontend
                    port:
                      number: 8501
  - apiVersion: networking.k8s.io/v1
    kind: Ingress
    metadata:
      name: dev-dentari-api
      namespace: dev-dentari
      labels:
        app: dev-dentari
      annotations:
        kubernetes.io/ingress.class: traefik
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
    spec:
      tls:
        - secretName: dev-dentari-tls
          hosts:
            - dev-api-dentari.edentlab.hu
      rules:
        - host: dev-api-dentari.edentlab.hu
          http:
            paths:
              - path: /
                pathType: Prefix
                backend:
                  service:
                    name: dev-backend
                    port:
                      number: 8000
